---
title: "Manuscripts in Rmarkdown"
author: "Brad Duthie"
date: "23 October 2019"
output:
  powerpoint_presentation: default
  ioslides_presentation: default
  beamer_presentation:
    theme: "default"
    colortheme: "default"
    fonttheme: "default"
  slidy_presentation: default
header-includes:
- \usepackage{hyperref}
colorlinks: true
linkcolor: blue
urlcolor: blue
---


## Objectives for learning Rmarkdown

<hr>

1. **Understand the features of Rmarkdown and why using it to write scientific documents may be useful**
2. **Create an Rmarkdown file and assemble it into an HTML, PDF, or DOCX document using knitr in Rstudio**
3. **Apply basic integration of R code into Rmarkdown to analyse data and plot results in output**
4. **Be able to navigate to the [accompanying Rmarkdown notes](https://stirlingcodingclub.github.io/Manuscripts_in_Rmarkdown/Rmarkdown_notes.html) and make use of them for additional tools**
5. **Continue asking questions and sharing tips in the Rmarkdown repository [issues page](https://github.com/StirlingCodingClub/Manuscripts_in_Rmarkdown/issues) on GitHub**

<hr>

## Where did Rmarkdown come from?

| Microsoft Word (1983)          |  \LaTeX (1980)                     |
| ------------------------------ | --------------------------------- |
| - Used in the life sciences    | - Used in maths and physics       |
| - What you see is what you get | - Edit files in [plain text](https://en.wikipedia.org/wiki/LaTeX) (code) |
| - Proprietary software         | - Free software                   |
| - **Low learning curve**       | - **High learning curve**         |
| - **No analysis integration**  | - **No analysis integration**     |

<hr>

**Rmarkdown** (2012) is free software with a **relatively low learning curve** in which authors write in plain text and can easily integrate R analyses, citations, and tables or figures.


## Why is Rmarkdown worth learning?

<hr>

- Learning is a relatively low additional time investment if already invested in R
- Produces high quality [HTML](https://stirlingcodingclub.github.io/Manuscripts_in_Rmarkdown/ms_history/ms_final.html), [PDF](https://github.com/StirlingCodingClub/Manuscripts_in_Rmarkdown/blob/224e0f3673aece576d5c859f5409b6c9b68a5565/ms.pdf), and [DOCX](https://github.com/StirlingCodingClub/Manuscripts_in_Rmarkdown/raw/224e0f3673aece576d5c859f5409b6c9b68a5565/ms.docx) documents with the push of a button from an [Rmd file](https://github.com/StirlingCodingClub/Manuscripts_in_Rmarkdown/blob/master/ms.Rmd) in Rstudio
- Removes the need to format citations manually (with BibTeX)
- Allows users to insert images and equations seamlessly
- **Complete integration of data analysis and manuscript** (no copy-pasting when values or figures change)

<hr>

**You do not need to learn everything at once for Rmarkdown to be useful. If you get stuck or cannot figure out how to do something, you can always knit a DOCX and work from there.**






